### ISSUE TITLE
Add plugable type codec

### ISSUE THREAD

**Issue by aamalev** [aioworkers/aioworkers-pg#1]
Work with json need codec https://magicstack.github.io/asyncpg/current/usage.html#type-conversion
```
await conn.set_type_codec(
            'json',
            encoder=json.dumps,
            decoder=json.loads,
            schema='pg_catalog'
        )
```

Set with create pool(init=…)

For asyncpgsa for json encoder=lambda x: x

**Comment by abogushov** [comment]
@aamalev  I guess this is implemented.

**Comment by aamalev** [comment]
I think the connector needs a parameter in the config
```
pg:
  cls: aioworkers_pg.base.Connector
  connection:
    init: mymodule.init_connection_coro
```

By default init maybe set as `aioworkers_pg.base.default_init`

**Comment by aamalev** [comment]
Still have a fantasy on the topic
```
pool:
  cls: ...
  codecs:
    json: aioworkers_pg.codecs.JsonCodec
    point: aioworkers_pg.codecs.geo.Point
    polygon: mygeomodule.PolygonCodec
    ...
```

But I don’t know how much such a feature is in demand
