### ISSUE TITLE
Pass extra parameters from config to create_pool

### ISSUE THREAD

**Issue by abogushov** [aioworkers/aioworkers-pg#12]
asyncpgsa.create_pool and asyncpg.create_pool can get extra parameters, for instance min_size, max_size. We can add pool node to configure it:

```yaml
db:
  cls: aioworkers_pg.base.Connector
  dsn: postgresql:///test
  pool:
    min_size: 1
    max_size: 20
```
