### ISSUE TITLE
Custom codecs support

### ISSUE THREAD

**Issue by abogushov** [aioworkers/aioworkers-pg#15]
Still have a fantasy on the topic
```
pool:
  cls: ...
  codecs:
    json: aioworkers_pg.codecs.JsonCodec
    point: aioworkers_pg.codecs.geo.Point
    polygon: mygeomodule.PolygonCodec
    ...
```

But I don’t know how much such a feature is in demand

_Originally posted by @aamalev in https://github.com/aioworkers/aioworkers-pg/issues/1#issuecomment-778854629_
